language: php

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local

env:
  global:
    - GH_USER_NAME: "Piotr Obidowski"
    - GH_USER_EMAIL: pobidowski@webowy.agency
    - GH_REF: github.com/Webowy/zend-pdf.git


before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - travis_retry php ./vendor/bin/coveralls