<?php
namespace Webowy\Pdf\View\Model;

use Zend\View\Model\ViewModel;

/**
 * Class PdfModel
 * @package Webowy\Pdf\View\Model
 */
class PdfModel extends ViewModel
{
    /**
     * Renderer options
     * @var array
     */
    protected $options = [
        'author' => 'Webowy',
        'title' => 'PDF generated by Webowy',
        'subject' => 'PDF',
        'keywords' => 'Webowy, PDF',
        'pageOrientation' => 'P',
        'pageUnit' => 'mm',
        'format' => 'A4',
        'attachments' => []
    ];

    /**
     * PDF probably won't need to be captured into a
     * a parent container by default.
     *
     * @var string
     */
    protected $captureTo = null;

    /**
     * PDF is usually terminal
     *
     * @var bool
     */
    protected $terminate = true;
}
